import * as vscode from 'vscode';

export async function generateERPModule(root: vscode.Uri, modules: string[], ctx: vscode.ExtensionContext, features: any) {
  const base = vscode.Uri.joinPath(root, 'shelb-generated', 'erp');
  await vscode.workspace.fs.createDirectory(base);

  for (const m of modules) {
    const file = vscode.Uri.joinPath(base, `${m}.md`);
    const content = `# ${m}

Generated by Shelb Snippets

- Module: ${m}
- Created: ${new Date().toISOString()}
`;
    await writeFile(file, content);
  }
}

async function writeFile(uri: vscode.Uri, content: string) {
  const encoder = new TextEncoder();
  await vscode.workspace.fs.writeFile(uri, encoder.encode(content));
}
