"""Generate snippets/ecommerce-auth-blocks.code-snippets.

Produces 20 selogin0X and 20 seregister0X advanced snippets (React + TS + Tailwind).
All snippets are self-contained, no external deps.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "snippets" / "ecommerce-auth-blocks.code-snippets"


def block(name, prefix, description, body_lines):
    """Build a snippet entry; body_lines is a list of strings (no trailing newlines)."""
    return name, {
        "prefix": prefix,
        "description": description,
        "body": body_lines,
    }


# ---------- LOGIN BUILDERS ----------

def login_basic(component, title, subtitle, api, redirect, theme="light", id_field="email"):
    """Standard email/password login form. theme = 'light' | 'dark'."""
    wrap_bg = "bg-gray-50" if theme == "light" else "bg-gray-950"
    card_bg = "bg-white" if theme == "light" else "bg-gray-900 border border-gray-800"
    text_h = "text-gray-900" if theme == "light" else "text-white"
    text_p = "text-gray-500" if theme == "light" else "text-gray-400"
    label = "text-gray-700" if theme == "light" else "text-gray-300"
    input_cls = (
        "border-gray-300 bg-white text-gray-900"
        if theme == "light"
        else "border-gray-700 bg-gray-800 text-gray-100"
    )
    field_type = "email" if id_field == "email" else "tel"
    field_label = "Email" if id_field == "email" else "Mobile number"
    field_ph = "you@store.com" if id_field == "email" else "+91 98765 43210"
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        f"export default function ${{1:{component}}}() {{",
        f"  const [{id_field}, set{id_field.capitalize()}] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [loading, setLoading] = useState(false);",
        "  const [error, setError] = useState<string | null>(null);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    setError(null);",
        "    try {",
        f"      const res = await fetch(\"${{2:{api}}}\", {{",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        f"        body: JSON.stringify({{ {id_field}, password }}),",
        "      });",
        "      if (!res.ok) throw new Error(\"Invalid credentials.\");",
        f"      window.location.href = \"${{3:{redirect}}}\";",
        "    } catch (err) {",
        "      setError((err as Error).message);",
        "    } finally {",
        "      setLoading(false);",
        "    }",
        "  }",
        "",
        "  return (",
        f"    <div className=\"min-h-screen flex items-center justify-center {wrap_bg} px-4\">",
        f"      <form onSubmit={{handleSubmit}} className=\"w-full max-w-md {card_bg} rounded-2xl shadow-lg p-8 space-y-6\">",
        "        <header className=\"text-center\">",
        f"          <h1 className=\"text-2xl font-semibold {text_h}\">${{4:{title}}}</h1>",
        f"          <p className=\"mt-1 text-sm {text_p}\">${{5:{subtitle}}}</p>",
        "        </header>",
        "        {error && <div role=\"alert\" className=\"rounded-md bg-red-50 text-red-700 px-3 py-2 text-sm\">{error}</div>}",
        "        <div className=\"space-y-1\">",
        f"          <label className=\"block text-sm font-medium {label}\">{field_label}</label>",
        f"          <input type=\"{field_type}\" required value={{{id_field}}} onChange={{(e) => set{id_field.capitalize()}(e.target.value)}} placeholder=\"{field_ph}\" className=\"w-full rounded-md border {input_cls} px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500\" />",
        "        </div>",
        "        <div className=\"space-y-1\">",
        f"          <label className=\"block text-sm font-medium {label}\">Password</label>",
        f"          <input type=\"password\" required value={{password}} onChange={{(e) => setPassword(e.target.value)}} className=\"w-full rounded-md border {input_cls} px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500\" />",
        "        </div>",
        "        <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">",
        "          {loading ? \"Signing in…\" : \"Sign in\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_otp():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:OtpLogin}() {",
        "  const [phone, setPhone] = useState(\"\");",
        "  const [otp, setOtp] = useState(\"\");",
        "  const [step, setStep] = useState<\"phone\" | \"otp\">(\"phone\");",
        "  const [loading, setLoading] = useState(false);",
        "  const [error, setError] = useState<string | null>(null);",
        "",
        "  async function sendOtp(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    setError(null);",
        "    try {",
        "      await fetch(\"${2:/api/auth/otp/send}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ phone }),",
        "      });",
        "      setStep(\"otp\");",
        "    } catch { setError(\"Could not send OTP.\"); }",
        "    finally { setLoading(false); }",
        "  }",
        "",
        "  async function verifyOtp(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    setError(null);",
        "    try {",
        "      const res = await fetch(\"${3:/api/auth/otp/verify}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ phone, otp }),",
        "      });",
        "      if (!res.ok) throw new Error(\"Invalid OTP.\");",
        "      window.location.href = \"${4:/account}\";",
        "    } catch (err) { setError((err as Error).message); }",
        "    finally { setLoading(false); }",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <div className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-6\">",
        "        <header className=\"text-center\">",
        "          <h1 className=\"text-2xl font-semibold text-gray-900\">Login with OTP</h1>",
        "          <p className=\"mt-1 text-sm text-gray-500\">We'll send a one-time code to your phone.</p>",
        "        </header>",
        "        {error && <div role=\"alert\" className=\"rounded-md bg-red-50 text-red-700 px-3 py-2 text-sm\">{error}</div>}",
        "        {step === \"phone\" ? (",
        "          <form onSubmit={sendOtp} className=\"space-y-4\">",
        "            <input type=\"tel\" required placeholder=\"Mobile number\" value={phone} onChange={(e) => setPhone(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500\" />",
        "            <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">",
        "              {loading ? \"Sending…\" : \"Send OTP\"}",
        "            </button>",
        "          </form>",
        "        ) : (",
        "          <form onSubmit={verifyOtp} className=\"space-y-4\">",
        "            <input type=\"text\" inputMode=\"numeric\" maxLength={6} required placeholder=\"6-digit code\" value={otp} onChange={(e) => setOtp(e.target.value)} className=\"w-full text-center tracking-[0.5em] rounded-md border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500\" />",
        "            <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">",
        "              {loading ? \"Verifying…\" : \"Verify & continue\"}",
        "            </button>",
        "            <button type=\"button\" onClick={() => setStep(\"phone\")} className=\"w-full text-sm text-blue-600 hover:underline\">Change number</button>",
        "          </form>",
        "        )}",
        "        $0",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]


def login_social():
    return [
        "import React from \"react\";",
        "",
        "export default function ${1:SocialLogin}() {",
        "  function continueWith(provider: string) {",
        "    window.location.href = `${2:/api/auth/social}/${provider}`;",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <div className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-6\">",
        "        <header className=\"text-center\">",
        "          <h1 className=\"text-2xl font-semibold text-gray-900\">Sign in to ${3:Shelb Store}</h1>",
        "          <p className=\"mt-1 text-sm text-gray-500\">Continue with your favourite account</p>",
        "        </header>",
        "        <div className=\"space-y-3\">",
        "          <button onClick={() => continueWith(\"google\")} className=\"w-full flex items-center justify-center gap-2 border border-gray-300 rounded-md px-4 py-2 hover:bg-gray-50\">",
        "            <span className=\"text-sm font-medium text-gray-700\">Continue with Google</span>",
        "          </button>",
        "          <button onClick={() => continueWith(\"facebook\")} className=\"w-full flex items-center justify-center gap-2 bg-[#1877F2] text-white rounded-md px-4 py-2 hover:opacity-90\">",
        "            <span className=\"text-sm font-medium\">Continue with Facebook</span>",
        "          </button>",
        "          <button onClick={() => continueWith(\"apple\")} className=\"w-full flex items-center justify-center gap-2 bg-black text-white rounded-md px-4 py-2 hover:opacity-90\">",
        "            <span className=\"text-sm font-medium\">Continue with Apple</span>",
        "          </button>",
        "        </div>",
        "        <div className=\"relative\">",
        "          <div className=\"absolute inset-0 flex items-center\"><span className=\"w-full border-t border-gray-200\"></span></div>",
        "          <div className=\"relative flex justify-center text-xs uppercase\"><span className=\"bg-white px-2 text-gray-400\">or</span></div>",
        "        </div>",
        "        <a href=\"${4:/login/email}\" className=\"block text-center text-sm text-blue-600 hover:underline\">Sign in with email instead</a>",
        "        $0",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]


def login_checkout():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:CheckoutLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [loading, setLoading] = useState(false);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/checkout/shipping}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen bg-gray-50 py-10 px-4\">",
        "      <div className=\"max-w-3xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6\">",
        "        <div className=\"md:col-span-2 bg-white rounded-2xl shadow p-8 space-y-6\">",
        "          <header>",
        "            <p className=\"text-xs uppercase tracking-wide text-blue-600 font-semibold\">Step 1 of 3</p>",
        "            <h1 className=\"text-xl font-semibold text-gray-900 mt-1\">Sign in to continue checkout</h1>",
        "          </header>",
        "          <form onSubmit={handleSubmit} className=\"space-y-4\">",
        "            <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "            <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "            <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">",
        "              {loading ? \"Signing in…\" : \"Sign in & continue\"}",
        "            </button>",
        "            <a href=\"${4:/checkout/guest}\" className=\"block text-center text-sm text-gray-600 hover:underline\">Continue as guest</a>",
        "          </form>",
        "        </div>",
        "        <aside className=\"bg-white rounded-2xl shadow p-6 h-fit\">",
        "          <h2 className=\"font-semibold text-gray-900\">Order summary</h2>",
        "          <p className=\"text-sm text-gray-500 mt-1\">3 items · ₹2,499</p>",
        "          <div className=\"mt-4 text-sm text-gray-600 space-y-1\">",
        "            <div className=\"flex justify-between\"><span>Subtotal</span><span>₹2,499</span></div>",
        "            <div className=\"flex justify-between\"><span>Shipping</span><span>Free</span></div>",
        "            <div className=\"flex justify-between font-semibold text-gray-900 pt-2 border-t\"><span>Total</span><span>₹2,499</span></div>",
        "          </div>",
        "        </aside>",
        "      </div>",
        "      $0",
        "    </div>",
        "  );",
        "}",
    ]


def login_wishlist_prompt():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:WishlistLoginPrompt}({ onClose }: { onClose?: () => void }) {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    onClose?.();",
        "  }",
        "",
        "  return (",
        "    <div className=\"fixed inset-0 bg-black/50 flex items-center justify-center px-4 z-50\">",
        "      <div className=\"w-full max-w-md bg-white rounded-2xl shadow-2xl p-8 space-y-5\">",
        "        <div className=\"text-center\">",
        "          <div className=\"mx-auto h-12 w-12 rounded-full bg-pink-100 text-pink-600 flex items-center justify-center text-2xl\">♥</div>",
        "          <h2 className=\"mt-3 text-lg font-semibold text-gray-900\">Save to your wishlist</h2>",
        "          <p className=\"text-sm text-gray-500 mt-1\">Sign in to save items and shop later from any device.</p>",
        "        </div>",
        "        <form onSubmit={handleSubmit} className=\"space-y-3\">",
        "          <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <button type=\"submit\" className=\"w-full rounded-md bg-pink-600 hover:bg-pink-700 text-white px-4 py-2 font-medium\">Sign in & save</button>",
        "        </form>",
        "        <button type=\"button\" onClick={onClose} className=\"w-full text-sm text-gray-500 hover:underline\">Maybe later</button>",
        "        $0",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]


def login_minimal():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:MinimalLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-white px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-sm space-y-5\">",
        "        <h1 className=\"text-3xl font-light text-gray-900 text-center\">${4:Shelb}</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full border-0 border-b border-gray-300 px-1 py-2 focus:border-black focus:outline-none focus:ring-0\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full border-0 border-b border-gray-300 px-1 py-2 focus:border-black focus:outline-none focus:ring-0\" />",
        "        <button type=\"submit\" className=\"w-full bg-black text-white py-2 text-sm tracking-wide\">SIGN IN</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_remember_me():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:RememberMeLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [remember, setRemember] = useState(true);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password, remember }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Welcome back</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <label className=\"flex items-center gap-2 text-sm text-gray-700\">",
        "          <input type=\"checkbox\" checked={remember} onChange={(e) => setRemember(e.target.checked)} className=\"rounded border-gray-300 text-blue-600\" />",
        "          Keep me signed in on this device",
        "        </label>",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Sign in</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_forgot():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:LoginForgotPassword}() {",
        "  const [mode, setMode] = useState<\"login\" | \"forgot\">(\"login\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [sent, setSent] = useState(false);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    if (mode === \"login\") {",
        "      await fetch(\"${2:/api/auth/login}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ email, password }),",
        "      });",
        "      window.location.href = \"${3:/account}\";",
        "    } else {",
        "      await fetch(\"${4:/api/auth/forgot}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ email }),",
        "      });",
        "      setSent(true);",
        "    }",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">",
        "          {mode === \"login\" ? \"Sign in\" : \"Reset password\"}",
        "        </h1>",
        "        {sent && <div className=\"rounded-md bg-green-50 text-green-700 px-3 py-2 text-sm\">Reset link sent. Check your inbox.</div>}",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        {mode === \"login\" && (",
        "          <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        )}",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">",
        "          {mode === \"login\" ? \"Sign in\" : \"Send reset link\"}",
        "        </button>",
        "        <button type=\"button\" onClick={() => { setMode(mode === \"login\" ? \"forgot\" : \"login\"); setSent(false); }} className=\"w-full text-sm text-blue-600 hover:underline\">",
        "          {mode === \"login\" ? \"Forgot password?\" : \"Back to sign in\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_validation():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:ValidatedLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [errors, setErrors] = useState<{ email?: string; password?: string }>({});",
        "",
        "  function validate() {",
        "    const e: typeof errors = {};",
        "    if (!/^\\S+@\\S+\\.\\S+$/.test(email)) e.email = \"Enter a valid email.\";",
        "    if (password.length < 8) e.password = \"Password must be at least 8 characters.\";",
        "    setErrors(e);",
        "    return Object.keys(e).length === 0;",
        "  }",
        "",
        "  async function handleSubmit(ev: FormEvent<HTMLFormElement>) {",
        "    ev.preventDefault();",
        "    if (!validate()) return;",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} noValidate className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Sign in</h1>",
        "        <div>",
        "          <input type=\"email\" placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          {errors.email && <p className=\"mt-1 text-xs text-red-600\">{errors.email}</p>}",
        "        </div>",
        "        <div>",
        "          <input type=\"password\" placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          {errors.password && <p className=\"mt-1 text-xs text-red-600\">{errors.password}</p>}",
        "        </div>",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Sign in</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_loading():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:LoadingLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [loading, setLoading] = useState(false);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    await new Promise((r) => setTimeout(r, 1200));",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    setLoading(false);",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Sign in</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} disabled={loading} className=\"w-full rounded-md border border-gray-300 px-3 py-2 disabled:bg-gray-50\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} disabled={loading} className=\"w-full rounded-md border border-gray-300 px-3 py-2 disabled:bg-gray-50\" />",
        "        <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60 flex items-center justify-center gap-2\">",
        "          {loading && <span className=\"inline-block h-4 w-4 rounded-full border-2 border-white border-t-transparent animate-spin\" />}",
        "          {loading ? \"Signing in…\" : \"Sign in\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_order_tracking():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:OrderTrackingLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/orders}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-5\">",
        "        <div className=\"text-center\">",
        "          <div className=\"mx-auto h-12 w-12 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-xl\">📦</div>",
        "          <h1 className=\"mt-3 text-2xl font-semibold text-gray-900\">Track your order</h1>",
        "          <p className=\"mt-1 text-sm text-gray-500\">Sign in to view live status of your shipments.</p>",
        "        </div>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Sign in & track</button>",
        "        <a href=\"${4:/orders/guest-track}\" className=\"block text-center text-sm text-blue-600 hover:underline\">Track without signing in</a>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_loyalty():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:LoyaltyLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/rewards}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-amber-50 to-orange-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-5\">",
        "        <div className=\"rounded-xl bg-amber-100 text-amber-900 p-4 text-sm\">",
        "          <p className=\"font-semibold\">🎁 Earn 100 points on every order</p>",
        "          <p className=\"text-amber-800 mt-1\">Sign in to view your loyalty balance and redeem rewards.</p>",
        "        </div>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-amber-600 hover:bg-amber-700 text-white px-4 py-2 font-medium\">Sign in & earn</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def login_guest():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:GuestCheckoutLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/checkout}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen bg-gray-50 py-10 px-4\">",
        "      <div className=\"max-w-3xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-6\">",
        "        <form onSubmit={handleSubmit} className=\"bg-white rounded-2xl shadow p-6 space-y-4\">",
        "          <h2 className=\"font-semibold text-gray-900\">Returning customer</h2>",
        "          <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Sign in</button>",
        "        </form>",
        "        <div className=\"bg-white rounded-2xl shadow p-6 space-y-4\">",
        "          <h2 className=\"font-semibold text-gray-900\">New customer</h2>",
        "          <p className=\"text-sm text-gray-500\">Skip the account — checkout as guest. You can create an account after.</p>",
        "          <a href=\"${4:/checkout/guest}\" className=\"block text-center rounded-md border border-gray-300 hover:bg-gray-50 px-4 py-2 text-sm font-medium text-gray-700\">Continue as guest</a>",
        "        </div>",
        "      </div>",
        "      $0",
        "    </div>",
        "  );",
        "}",
    ]


def login_2fa():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:TwoFactorLogin}() {",
        "  const [step, setStep] = useState<\"password\" | \"2fa\">(\"password\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [code, setCode] = useState(\"\");",
        "",
        "  async function submitPassword(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    setStep(\"2fa\");",
        "  }",
        "",
        "  async function submit2fa(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${3:/api/auth/2fa}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, code }),",
        "    });",
        "    window.location.href = \"${4:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <div className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        {step === \"password\" ? (",
        "          <form onSubmit={submitPassword} className=\"space-y-4\">",
        "            <h1 className=\"text-2xl font-semibold text-gray-900\">Sign in</h1>",
        "            <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "            <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "            <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Continue</button>",
        "          </form>",
        "        ) : (",
        "          <form onSubmit={submit2fa} className=\"space-y-4\">",
        "            <h1 className=\"text-2xl font-semibold text-gray-900\">Two-factor verification</h1>",
        "            <p className=\"text-sm text-gray-500\">Enter the 6-digit code from your authenticator app.</p>",
        "            <input type=\"text\" inputMode=\"numeric\" maxLength={6} required placeholder=\"123 456\" value={code} onChange={(e) => setCode(e.target.value)} className=\"w-full text-center tracking-[0.5em] rounded-md border border-gray-300 px-3 py-2\" />",
        "            <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Verify & continue</button>",
        "          </form>",
        "        )}",
        "        $0",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]


def login_session_expired():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:SessionExpiredLogin}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/login}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    const back = new URLSearchParams(window.location.search).get(\"return\") || \"${3:/account}\";",
        "    window.location.href = back;",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <div className=\"rounded-md bg-amber-50 border border-amber-200 text-amber-800 px-3 py-2 text-sm\">",
        "          Your session has expired. Please sign in again to continue.",
        "        </div>",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Sign in again</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Continue where you left off</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


# ---------- REGISTER BUILDERS ----------

def register_basic(component, title, subtitle, api, redirect, theme="light", role=""):
    wrap_bg = "bg-gray-50" if theme == "light" else "bg-gray-950"
    card_bg = "bg-white" if theme == "light" else "bg-gray-900 border border-gray-800"
    text_h = "text-gray-900" if theme == "light" else "text-white"
    text_p = "text-gray-500" if theme == "light" else "text-gray-400"
    input_cls = (
        "border-gray-300 bg-white"
        if theme == "light"
        else "border-gray-700 bg-gray-800 text-gray-100"
    )
    role_field = []
    if role:
        role_field = [
            "  const [role] = useState(\"" + role + "\");",
        ]
    role_payload = ", role" if role else ""
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        f"export default function ${{1:{component}}}() {{",
        "  const [name, setName] = useState(\"\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [loading, setLoading] = useState(false);",
        *role_field,
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        f"    await fetch(\"${{2:{api}}}\", {{",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        f"      body: JSON.stringify({{ name, email, password{role_payload} }}),",
        "    });",
        "    setLoading(false);",
        f"    window.location.href = \"${{3:{redirect}}}\";",
        "  }",
        "",
        "  return (",
        f"    <div className=\"min-h-screen flex items-center justify-center {wrap_bg} px-4\">",
        f"      <form onSubmit={{handleSubmit}} className=\"w-full max-w-md {card_bg} rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <header>",
        f"          <h1 className=\"text-2xl font-semibold {text_h}\">${{4:{title}}}</h1>",
        f"          <p className=\"text-sm {text_p} mt-1\">${{5:{subtitle}}}</p>",
        "        </header>",
        f"        <input required placeholder=\"Full name\" value={{name}} onChange={{(e) => setName(e.target.value)}} className=\"w-full rounded-md border {input_cls} px-3 py-2\" />",
        f"        <input type=\"email\" required placeholder=\"Email\" value={{email}} onChange={{(e) => setEmail(e.target.value)}} className=\"w-full rounded-md border {input_cls} px-3 py-2\" />",
        f"        <input type=\"password\" required placeholder=\"Password\" value={{password}} onChange={{(e) => setPassword(e.target.value)}} className=\"w-full rounded-md border {input_cls} px-3 py-2\" />",
        "        <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">",
        "          {loading ? \"Creating account…\" : \"Create account\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_quick():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:QuickRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-sm bg-white rounded-2xl shadow p-8 space-y-4\">",
        "        <h1 className=\"text-xl font-semibold text-gray-900\">Join in 30 seconds</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_phone_otp():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:PhoneOtpRegister}() {",
        "  const [phone, setPhone] = useState(\"\");",
        "  const [otp, setOtp] = useState(\"\");",
        "  const [name, setName] = useState(\"\");",
        "  const [step, setStep] = useState<1 | 2 | 3>(1);",
        "",
        "  async function next(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    if (step === 1) {",
        "      await fetch(\"${2:/api/auth/otp/send}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ phone }),",
        "      });",
        "      setStep(2);",
        "    } else if (step === 2) {",
        "      await fetch(\"${3:/api/auth/otp/verify}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ phone, otp }),",
        "      });",
        "      setStep(3);",
        "    } else {",
        "      await fetch(\"${4:/api/auth/register}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ phone, name }),",
        "      });",
        "      window.location.href = \"${5:/account}\";",
        "    }",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={next} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <p className=\"text-xs uppercase text-blue-600 font-semibold\">Step {step} of 3</p>",
        "        {step === 1 && (<><h1 className=\"text-2xl font-semibold text-gray-900\">Sign up with phone</h1><input type=\"tel\" required placeholder=\"Mobile number\" value={phone} onChange={(e) => setPhone(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" /></>)}",
        "        {step === 2 && (<><h1 className=\"text-2xl font-semibold text-gray-900\">Enter OTP</h1><input type=\"text\" inputMode=\"numeric\" maxLength={6} required placeholder=\"6-digit code\" value={otp} onChange={(e) => setOtp(e.target.value)} className=\"w-full text-center tracking-[0.5em] rounded-md border border-gray-300 px-3 py-2\" /></>)}",
        "        {step === 3 && (<><h1 className=\"text-2xl font-semibold text-gray-900\">Your name</h1><input required placeholder=\"Full name\" value={name} onChange={(e) => setName(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" /></>)}",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">",
        "          {step === 3 ? \"Create account\" : \"Continue\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_terms():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:TermsRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [agree, setAgree] = useState(false);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    if (!agree) return;",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create your account</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <label className=\"flex items-start gap-2 text-sm text-gray-600\">",
        "          <input type=\"checkbox\" checked={agree} onChange={(e) => setAgree(e.target.checked)} className=\"mt-0.5 rounded border-gray-300 text-blue-600\" />",
        "          <span>I agree to the <a href=\"${4:/terms}\" className=\"text-blue-600 hover:underline\">Terms</a> and <a href=\"${5:/privacy}\" className=\"text-blue-600 hover:underline\">Privacy Policy</a>.</span>",
        "        </label>",
        "        <button type=\"submit\" disabled={!agree} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">Create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_newsletter():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:NewsletterRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [subscribe, setSubscribe] = useState(true);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password, subscribe }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-50 to-rose-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-5\">",
        "        <div className=\"rounded-xl bg-pink-100 text-pink-900 p-3 text-sm\">📩 Get ₹100 off your first order when you subscribe.</div>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <label className=\"flex items-center gap-2 text-sm text-gray-700\">",
        "          <input type=\"checkbox\" checked={subscribe} onChange={(e) => setSubscribe(e.target.checked)} className=\"rounded border-gray-300 text-pink-600\" />",
        "          Send me deals & launch updates",
        "        </label>",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-pink-600 hover:bg-pink-700 text-white px-4 py-2 font-medium\">Create account & save ₹100</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_referral():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:ReferralRegister}() {",
        "  const [name, setName] = useState(\"\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [referral, setReferral] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ name, email, password, referral }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create account</h1>",
        "        <input required placeholder=\"Full name\" value={name} onChange={(e) => setName(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <div>",
        "          <label className=\"block text-sm font-medium text-gray-700\">Referral code (optional)</label>",
        "          <input placeholder=\"SHELB100\" value={referral} onChange={(e) => setReferral(e.target.value.toUpperCase())} className=\"w-full rounded-md border border-gray-300 px-3 py-2 mt-1\" />",
        "          <p className=\"mt-1 text-xs text-gray-500\">Both of you get ₹200 in store credit.</p>",
        "        </div>",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_validation():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:ValidatedRegister}() {",
        "  const [name, setName] = useState(\"\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [confirm, setConfirm] = useState(\"\");",
        "  const [errors, setErrors] = useState<Record<string, string>>({});",
        "",
        "  function validate() {",
        "    const e: Record<string, string> = {};",
        "    if (name.trim().length < 2) e.name = \"Enter your full name.\";",
        "    if (!/^\\S+@\\S+\\.\\S+$/.test(email)) e.email = \"Enter a valid email.\";",
        "    if (password.length < 8) e.password = \"Min 8 characters.\";",
        "    if (password !== confirm) e.confirm = \"Passwords do not match.\";",
        "    setErrors(e);",
        "    return Object.keys(e).length === 0;",
        "  }",
        "",
        "  async function handleSubmit(ev: FormEvent<HTMLFormElement>) {",
        "    ev.preventDefault();",
        "    if (!validate()) return;",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ name, email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  function Field({ label, name: f, type = \"text\", value, onChange }: any) {",
        "    return (",
        "      <div>",
        "        <input type={type} placeholder={label} value={value} onChange={(e) => onChange(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        {errors[f] && <p className=\"mt-1 text-xs text-red-600\">{errors[f]}</p>}",
        "      </div>",
        "    );",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} noValidate className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-4\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create account</h1>",
        "        <Field label=\"Full name\" name=\"name\" value={name} onChange={setName} />",
        "        <Field label=\"Email\" name=\"email\" type=\"email\" value={email} onChange={setEmail} />",
        "        <Field label=\"Password\" name=\"password\" type=\"password\" value={password} onChange={setPassword} />",
        "        <Field label=\"Confirm password\" name=\"confirm\" type=\"password\" value={confirm} onChange={setConfirm} />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_strength():
    return [
        "import React, { useState, useMemo, FormEvent } from \"react\";",
        "",
        "export default function ${1:PasswordStrengthRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  const score = useMemo(() => {",
        "    let s = 0;",
        "    if (password.length >= 8) s++;",
        "    if (/[A-Z]/.test(password)) s++;",
        "    if (/[0-9]/.test(password)) s++;",
        "    if (/[^A-Za-z0-9]/.test(password)) s++;",
        "    return s; // 0..4",
        "  }, [password]);",
        "",
        "  const labels = [\"Too weak\", \"Weak\", \"Okay\", \"Strong\", \"Excellent\"];",
        "  const colors = [\"bg-gray-200\", \"bg-red-400\", \"bg-amber-400\", \"bg-lime-500\", \"bg-emerald-500\"];",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    if (score < 3) return;",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create account</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <div>",
        "          <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <div className=\"mt-2 grid grid-cols-4 gap-1\">",
        "            {[0, 1, 2, 3].map((i) => (",
        "              <span key={i} className={`h-1.5 rounded ${i < score ? colors[score] : \"bg-gray-200\"}`} />",
        "            ))}",
        "          </div>",
        "          <p className=\"mt-1 text-xs text-gray-500\">Strength: {labels[score]}</p>",
        "        </div>",
        "        <button type=\"submit\" disabled={score < 3} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60\">Create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_loading():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:LoadingRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [loading, setLoading] = useState(false);",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    setLoading(true);",
        "    await new Promise((r) => setTimeout(r, 800));",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    setLoading(false);",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create account</h1>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} disabled={loading} className=\"w-full rounded-md border border-gray-300 px-3 py-2 disabled:bg-gray-50\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} disabled={loading} className=\"w-full rounded-md border border-gray-300 px-3 py-2 disabled:bg-gray-50\" />",
        "        <button type=\"submit\" disabled={loading} className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium disabled:opacity-60 flex items-center justify-center gap-2\">",
        "          {loading && <span className=\"inline-block h-4 w-4 rounded-full border-2 border-white border-t-transparent animate-spin\" />}",
        "          {loading ? \"Creating account…\" : \"Create account\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_social_options():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:RegisterSocial}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account}\";",
        "  }",
        "",
        "  function social(provider: string) {",
        "    window.location.href = `${4:/api/auth/social}/${provider}`;",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <div className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <h1 className=\"text-2xl font-semibold text-gray-900\">Create account</h1>",
        "        <div className=\"grid grid-cols-3 gap-2\">",
        "          <button onClick={() => social(\"google\")} className=\"border border-gray-300 rounded-md px-3 py-2 text-sm hover:bg-gray-50\">Google</button>",
        "          <button onClick={() => social(\"facebook\")} className=\"border border-gray-300 rounded-md px-3 py-2 text-sm hover:bg-gray-50\">Facebook</button>",
        "          <button onClick={() => social(\"apple\")} className=\"border border-gray-300 rounded-md px-3 py-2 text-sm hover:bg-gray-50\">Apple</button>",
        "        </div>",
        "        <div className=\"relative\"><div className=\"absolute inset-0 flex items-center\"><span className=\"w-full border-t border-gray-200\"></span></div><div className=\"relative flex justify-center text-xs uppercase\"><span className=\"bg-white px-2 text-gray-400\">or</span></div></div>",
        "        <form onSubmit={handleSubmit} className=\"space-y-3\">",
        "          <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Create account</button>",
        "        </form>",
        "        $0",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]


def register_2step():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:TwoStepRegister}() {",
        "  const [step, setStep] = useState<1 | 2>(1);",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "  const [code, setCode] = useState(\"\");",
        "",
        "  async function next(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    if (step === 1) {",
        "      await fetch(\"${2:/api/auth/register}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ email, password }),",
        "      });",
        "      setStep(2);",
        "    } else {",
        "      await fetch(\"${3:/api/auth/verify-email}\", {",
        "        method: \"POST\",",
        "        headers: { \"Content-Type\": \"application/json\" },",
        "        body: JSON.stringify({ email, code }),",
        "      });",
        "      window.location.href = \"${4:/account}\";",
        "    }",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={next} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-5\">",
        "        <div className=\"flex items-center gap-2 text-xs\">",
        "          <span className={`h-1.5 flex-1 rounded ${step >= 1 ? \"bg-blue-600\" : \"bg-gray-200\"}`} />",
        "          <span className={`h-1.5 flex-1 rounded ${step >= 2 ? \"bg-blue-600\" : \"bg-gray-200\"}`} />",
        "        </div>",
        "        {step === 1 ? (",
        "          <>",
        "            <h1 className=\"text-2xl font-semibold text-gray-900\">Step 1 · Your details</h1>",
        "            <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "            <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "          </>",
        "        ) : (",
        "          <>",
        "            <h1 className=\"text-2xl font-semibold text-gray-900\">Step 2 · Verify email</h1>",
        "            <p className=\"text-sm text-gray-500\">We sent a 6-digit code to {email}.</p>",
        "            <input type=\"text\" inputMode=\"numeric\" maxLength={6} required placeholder=\"123 456\" value={code} onChange={(e) => setCode(e.target.value)} className=\"w-full text-center tracking-[0.5em] rounded-md border border-gray-300 px-3 py-2\" />",
        "          </>",
        "        )}",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">",
        "          {step === 1 ? \"Continue\" : \"Verify & finish\"}",
        "        </button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_gst():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:GstRegister}() {",
        "  const [company, setCompany] = useState(\"\");",
        "  const [gstin, setGstin] = useState(\"\");",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register/business}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ company, gstin, email, password }),",
        "    });",
        "    window.location.href = \"${3:/business/dashboard}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gray-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-lg p-8 space-y-4\">",
        "        <header>",
        "          <h1 className=\"text-2xl font-semibold text-gray-900\">Register your business</h1>",
        "          <p className=\"text-sm text-gray-500 mt-1\">Get GST invoices on every order.</p>",
        "        </header>",
        "        <input required placeholder=\"Company / store name\" value={company} onChange={(e) => setCompany(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input required placeholder=\"GSTIN (e.g. 27AABCU9603R1ZM)\" value={gstin} onChange={(e) => setGstin(e.target.value.toUpperCase())} className=\"w-full rounded-md border border-gray-300 px-3 py-2 uppercase\" />",
        "        <input type=\"email\" required placeholder=\"Work email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 font-medium\">Create business account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


def register_welcome_bonus():
    return [
        "import React, { useState, FormEvent } from \"react\";",
        "",
        "export default function ${1:WelcomeBonusRegister}() {",
        "  const [email, setEmail] = useState(\"\");",
        "  const [password, setPassword] = useState(\"\");",
        "",
        "  async function handleSubmit(e: FormEvent<HTMLFormElement>) {",
        "    e.preventDefault();",
        "    await fetch(\"${2:/api/auth/register}\", {",
        "      method: \"POST\",",
        "      headers: { \"Content-Type\": \"application/json\" },",
        "      body: JSON.stringify({ email, password }),",
        "    });",
        "    window.location.href = \"${3:/account?welcome=1}\";",
        "  }",
        "",
        "  return (",
        "    <div className=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-emerald-50 to-teal-50 px-4\">",
        "      <form onSubmit={handleSubmit} className=\"w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-5\">",
        "        <div className=\"rounded-xl bg-emerald-100 text-emerald-900 p-4\">",
        "          <p className=\"font-semibold\">🎉 Welcome gift: ₹250 store credit</p>",
        "          <p className=\"text-sm text-emerald-800 mt-1\">Create your account and we'll drop ₹250 into your wallet.</p>",
        "        </div>",
        "        <input type=\"email\" required placeholder=\"Email\" value={email} onChange={(e) => setEmail(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <input type=\"password\" required placeholder=\"Password\" value={password} onChange={(e) => setPassword(e.target.value)} className=\"w-full rounded-md border border-gray-300 px-3 py-2\" />",
        "        <button type=\"submit\" className=\"w-full rounded-md bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 font-medium\">Claim ₹250 & create account</button>",
        "        $0",
        "      </form>",
        "    </div>",
        "  );",
        "}",
    ]


# ---------- ASSEMBLE FILE ----------

entries = []

# Login 01-20
entries.append(("Shelb E-com Login — Customer (selogin01)", {
    "prefix": "selogin01",
    "description": "Customer login form (React + TS + Tailwind, email + password, loading + error).",
    "body": login_basic("CustomerLogin", "Sign in to your account", "Welcome back to Shelb Store.", "/api/auth/login", "/account"),
}))
entries.append(("Shelb E-com Login — OTP (selogin02)", {
    "prefix": "selogin02",
    "description": "Two-step OTP login (phone + 6-digit code) with state machine.",
    "body": login_otp(),
}))
entries.append(("Shelb E-com Login — Social (selogin03)", {
    "prefix": "selogin03",
    "description": "Social login placeholder with Google / Facebook / Apple buttons.",
    "body": login_social(),
}))
entries.append(("Shelb E-com Login — Mobile-first (selogin04)", {
    "prefix": "selogin04",
    "description": "Mobile-first login using phone number as primary identifier.",
    "body": login_basic("MobileLogin", "Sign in", "Use your registered mobile number.", "/api/auth/login", "/account", id_field="phone"),
}))
entries.append(("Shelb E-com Login — Checkout (selogin05)", {
    "prefix": "selogin05",
    "description": "Inline checkout login with order summary sidebar.",
    "body": login_checkout(),
}))
entries.append(("Shelb E-com Login — Wishlist Prompt (selogin06)", {
    "prefix": "selogin06",
    "description": "Modal-style wishlist sign-in prompt with skip option.",
    "body": login_wishlist_prompt(),
}))
entries.append(("Shelb E-com Login — Account Portal (selogin07)", {
    "prefix": "selogin07",
    "description": "Customer account portal login screen.",
    "body": login_basic("AccountLogin", "Account login", "Manage orders, addresses and rewards.", "/api/auth/login", "/account"),
}))
entries.append(("Shelb E-com Login — Vendor Portal (selogin08)", {
    "prefix": "selogin08",
    "description": "Vendor portal login for multi-vendor marketplace.",
    "body": login_basic("VendorLogin", "Vendor portal", "Manage your store, orders, and payouts.", "/api/vendor/login", "/vendor/dashboard"),
}))
entries.append(("Shelb E-com Login — Admin (selogin09)", {
    "prefix": "selogin09",
    "description": "Admin login for marketplace operations team.",
    "body": login_basic("AdminLogin", "Admin sign in", "Internal access only.", "/api/admin/login", "/admin"),
}))
entries.append(("Shelb E-com Login — Dark (selogin10)", {
    "prefix": "selogin10",
    "description": "Dark-themed e-commerce login form.",
    "body": login_basic("DarkLogin", "Welcome back", "Premium members sign in here.", "/api/auth/login", "/account", theme="dark"),
}))
entries.append(("Shelb E-com Login — Minimal (selogin11)", {
    "prefix": "selogin11",
    "description": "Minimal centered login with underline-only inputs.",
    "body": login_minimal(),
}))
entries.append(("Shelb E-com Login — Remember Me (selogin12)", {
    "prefix": "selogin12",
    "description": "Login with a remember-me checkbox to persist session.",
    "body": login_remember_me(),
}))
entries.append(("Shelb E-com Login — Forgot Password (selogin13)", {
    "prefix": "selogin13",
    "description": "Login with inline forgot-password reset flow.",
    "body": login_forgot(),
}))
entries.append(("Shelb E-com Login — Validation (selogin14)", {
    "prefix": "selogin14",
    "description": "Login with regex email + min-length password validation and field errors.",
    "body": login_validation(),
}))
entries.append(("Shelb E-com Login — Loading State (selogin15)", {
    "prefix": "selogin15",
    "description": "Login with explicit loading spinner and disabled fields.",
    "body": login_loading(),
}))
entries.append(("Shelb E-com Login — Order Tracking (selogin16)", {
    "prefix": "selogin16",
    "description": "Login prompt designed for the 'track my order' funnel.",
    "body": login_order_tracking(),
}))
entries.append(("Shelb E-com Login — Loyalty Points (selogin17)", {
    "prefix": "selogin17",
    "description": "Login with loyalty rewards messaging and amber accent.",
    "body": login_loyalty(),
}))
entries.append(("Shelb E-com Login — Guest Checkout (selogin18)", {
    "prefix": "selogin18",
    "description": "Side-by-side login and 'continue as guest' for checkout.",
    "body": login_guest(),
}))
entries.append(("Shelb E-com Login — 2FA Placeholder (selogin19)", {
    "prefix": "selogin19",
    "description": "Login with two-factor authentication second step.",
    "body": login_2fa(),
}))
entries.append(("Shelb E-com Login — Session Expired (selogin20)", {
    "prefix": "selogin20",
    "description": "Session-expired re-login with return-url handling.",
    "body": login_session_expired(),
}))

# Register 01-20
entries.append(("Shelb E-com Register — Customer (seregister01)", {
    "prefix": "seregister01",
    "description": "Customer registration with name, email, password.",
    "body": register_basic("CustomerRegister", "Create your account", "Shop, save, and track all in one place.", "/api/auth/register", "/account"),
}))
entries.append(("Shelb E-com Register — Quick (seregister02)", {
    "prefix": "seregister02",
    "description": "Quick 2-field register for fastest signup.",
    "body": register_quick(),
}))
entries.append(("Shelb E-com Register — Phone + OTP (seregister03)", {
    "prefix": "seregister03",
    "description": "Phone-first registration with OTP verification and name step.",
    "body": register_phone_otp(),
}))
entries.append(("Shelb E-com Register — Mobile-first (seregister04)", {
    "prefix": "seregister04",
    "description": "Mobile-first register form using phone as ID.",
    "body": register_basic("MobileRegister", "Sign up", "Use your mobile number to get started.", "/api/auth/register", "/account"),
}))
entries.append(("Shelb E-com Register — Checkout (seregister05)", {
    "prefix": "seregister05",
    "description": "Lean register form shown inline during checkout.",
    "body": register_basic("CheckoutRegister", "Save my details for next time", "Create an account in one step.", "/api/auth/register", "/checkout/shipping"),
}))
entries.append(("Shelb E-com Register — Account Portal (seregister06)", {
    "prefix": "seregister06",
    "description": "Account portal register with name + email + password.",
    "body": register_basic("AccountRegister", "Create your customer account", "Track orders, save addresses, and unlock rewards.", "/api/auth/register", "/account"),
}))
entries.append(("Shelb E-com Register — Vendor (seregister07)", {
    "prefix": "seregister07",
    "description": "Vendor signup for multi-vendor marketplaces.",
    "body": register_basic("VendorRegister", "Sell on Shelb", "Reach millions of customers across India.", "/api/vendor/register", "/vendor/onboarding", role="vendor"),
}))
entries.append(("Shelb E-com Register — Admin Invite (seregister08)", {
    "prefix": "seregister08",
    "description": "Admin-invite register form (used after invitation email).",
    "body": register_basic("AdminInviteRegister", "Set up your admin account", "Complete the invite to continue.", "/api/admin/accept-invite", "/admin", role="admin"),
}))
entries.append(("Shelb E-com Register — Dark (seregister09)", {
    "prefix": "seregister09",
    "description": "Dark-themed register screen.",
    "body": register_basic("DarkRegister", "Join Shelb Premium", "Members-only deals and early access.", "/api/auth/register", "/account", theme="dark"),
}))
entries.append(("Shelb E-com Register — Minimal (seregister10)", {
    "prefix": "seregister10",
    "description": "Minimal centered register form.",
    "body": register_basic("MinimalRegister", "Create account", "It only takes a minute.", "/api/auth/register", "/account"),
}))
entries.append(("Shelb E-com Register — Terms (seregister11)", {
    "prefix": "seregister11",
    "description": "Register with Terms & Privacy Policy checkbox gating submit.",
    "body": register_terms(),
}))
entries.append(("Shelb E-com Register — Newsletter (seregister12)", {
    "prefix": "seregister12",
    "description": "Register with marketing newsletter opt-in toggle.",
    "body": register_newsletter(),
}))
entries.append(("Shelb E-com Register — Referral (seregister13)", {
    "prefix": "seregister13",
    "description": "Register with optional referral code field.",
    "body": register_referral(),
}))
entries.append(("Shelb E-com Register — Validation (seregister14)", {
    "prefix": "seregister14",
    "description": "Register with full field validation (email regex, password length, confirm match).",
    "body": register_validation(),
}))
entries.append(("Shelb E-com Register — Strength Meter (seregister15)", {
    "prefix": "seregister15",
    "description": "Register with live password strength meter.",
    "body": register_strength(),
}))
entries.append(("Shelb E-com Register — Loading (seregister16)", {
    "prefix": "seregister16",
    "description": "Register form with explicit loading spinner.",
    "body": register_loading(),
}))
entries.append(("Shelb E-com Register — Social (seregister17)", {
    "prefix": "seregister17",
    "description": "Register with Google / Facebook / Apple social options.",
    "body": register_social_options(),
}))
entries.append(("Shelb E-com Register — Two-step (seregister18)", {
    "prefix": "seregister18",
    "description": "Two-step register with email verification code.",
    "body": register_2step(),
}))
entries.append(("Shelb E-com Register — GST (B2B) (seregister19)", {
    "prefix": "seregister19",
    "description": "Business register capturing company name + GSTIN for B2B invoicing.",
    "body": register_gst(),
}))
entries.append(("Shelb E-com Register — Welcome Bonus (seregister20)", {
    "prefix": "seregister20",
    "description": "Register with welcome-bonus messaging and store-credit incentive.",
    "body": register_welcome_bonus(),
}))


def main():
    data = {name: body for name, body in entries}
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT} with {len(data)} snippets.")


if __name__ == "__main__":
    main()
